// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkfxD9rKhaKk1MGe93nb63UJB-zZKqiUA',
    appId: '1:148817926259:web:182dd5e415f330dc22b206',
    messagingSenderId: '148817926259',
    projectId: 'my-fyp-d2c05',
    authDomain: 'my-fyp-d2c05.firebaseapp.com',
    databaseURL: 'https://my-fyp-d2c05-default-rtdb.firebaseio.com',
    storageBucket: 'my-fyp-d2c05.appspot.com',
    measurementId: 'G-ZSEPRWVR37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jF7cklkFOFzZEAUEK8hKVOHDt41qSlY',
    appId: '1:148817926259:android:160726313054e2b222b206',
    messagingSenderId: '148817926259',
    projectId: 'my-fyp-d2c05',
    databaseURL: 'https://my-fyp-d2c05-default-rtdb.firebaseio.com',
    storageBucket: 'my-fyp-d2c05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZldV_j8FlsZDXSwTf-Me9DIRrFtkFKVk',
    appId: '1:148817926259:ios:b402f9ef937f42b922b206',
    messagingSenderId: '148817926259',
    projectId: 'my-fyp-d2c05',
    databaseURL: 'https://my-fyp-d2c05-default-rtdb.firebaseio.com',
    storageBucket: 'my-fyp-d2c05.appspot.com',
    iosClientId: '148817926259-6pisb78fped3jbstlkd292in79otao55.apps.googleusercontent.com',
    iosBundleId: 'com.example.adilFyp',
  );
}
